language: cpp
script:
  - sh tools/get_phsem
  - sh -x bootstrap.sh
  - env CFLAGS="-Wall -Wextra -I$HOME/pthsem/include -L$HOME/pthsem/lib" CPPFLAGS="-Wall -Wextra -I$HOME/pthsem/include -L$HOME/pthsem/lib" ./configure --without-pth-test --disable-systemd
  - make
  - sh tools/test.sh
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
    - $HOME/pthsem
sudo: false
